-- genere

INSERT INTO genere VALUES(1,'Anime Features');
INSERT INTO genere VALUES(2,'Children & Family Movies');
INSERT INTO genere VALUES(3,'Classic & Cult TV');
INSERT INTO genere VALUES(4,'Classic Movies');
INSERT INTO genere VALUES(5,'Comedies');
INSERT INTO genere VALUES(6,'Crime TV Shows');
INSERT INTO genere VALUES(7,'Cult Movies');
INSERT INTO genere VALUES(8,'Documentaries');
INSERT INTO genere VALUES(9,'Docuseries');
INSERT INTO genere VALUES(10,'Dramas');
INSERT INTO genere VALUES(11,'Faith & Spirituality');
INSERT INTO genere VALUES(12,'Horror Movies');
INSERT INTO genere VALUES(13,'Independent Movies');
INSERT INTO genere VALUES(14,'International Movies');
INSERT INTO genere VALUES(15,'International TV Shows');
INSERT INTO genere VALUES(16,'Kids'' TV');
INSERT INTO genere VALUES(17,'Korean TV Shows');
INSERT INTO genere VALUES(18,'LGBTQ Movies');
INSERT INTO genere VALUES(19,'Music & Musicals');
INSERT INTO genere VALUES(20,'Reality TV');
INSERT INTO genere VALUES(21,'Romantic Movies');
INSERT INTO genere VALUES(22,'Romantic TV Shows');
INSERT INTO genere VALUES(23,'Science & Nature TV');
INSERT INTO genere VALUES(24,'Sci-Fi & Fantasy');
INSERT INTO genere VALUES(25,'Spanish-Language TV Shows');
INSERT INTO genere VALUES(26,'Sports Movies');
INSERT INTO genere VALUES(27,'Stand-Up Comedy');
INSERT INTO genere VALUES(28,'Stand-Up Comedy & Talk Shows');
INSERT INTO genere VALUES(29,'Teen TV Shows');
INSERT INTO genere VALUES(30,'Thrillers');
INSERT INTO genere VALUES(31,'TV Action & Adventure');
INSERT INTO genere VALUES(32,'TV Comedies');
INSERT INTO genere VALUES(33,'TV Dramas');
INSERT INTO genere VALUES(34,'TV Horror');
INSERT INTO genere VALUES(35,'TV Mysteries');
INSERT INTO genere VALUES(36,'TV Sci-Fi & Fantasy');
INSERT INTO genere VALUES(37,'TV Thrillers');
INSERT INTO genere VALUES(38,'Action & Adventure');
INSERT INTO genere VALUES(39,'Anime Features');
INSERT INTO genere VALUES(40,'Anime Series');
INSERT INTO genere VALUES(41,'British TV Shows');
INSERT INTO genere VALUES(42,'Children & Family Movies');
INSERT INTO genere VALUES(43,'Classic & Cult TV');
INSERT INTO genere VALUES(44,'Classic Movies');
INSERT INTO genere VALUES(45,'Comedies');
INSERT INTO genere VALUES(46,'Crime TV Shows');
INSERT INTO genere VALUES(47,'Cult Movies');
INSERT INTO genere VALUES(48,'Documentaries');
INSERT INTO genere VALUES(49,'Docuseries');
INSERT INTO genere VALUES(50,'Dramas');
INSERT INTO genere VALUES(51,'Horror Movies');
INSERT INTO genere VALUES(52,'Independent Movies');
INSERT INTO genere VALUES(53,'International Movies');
INSERT INTO genere VALUES(54,'International TV Shows');
INSERT INTO genere VALUES(55,'Kids'' TV');
INSERT INTO genere VALUES(56,'LGBTQ Movies');
INSERT INTO genere VALUES(57,'Movies');
INSERT INTO genere VALUES(58,'Music & Musicals');
INSERT INTO genere VALUES(59,'Reality TV');
INSERT INTO genere VALUES(60,'Romantic Movies');
INSERT INTO genere VALUES(61,'Romantic TV Shows');
INSERT INTO genere VALUES(62,'Sci-Fi & Fantasy');
INSERT INTO genere VALUES(63,'Spanish-Language TV Shows');
INSERT INTO genere VALUES(64,'Sports Movies');
INSERT INTO genere VALUES(65,'Stand-Up Comedy');
INSERT INTO genere VALUES(66,'Stand-Up Comedy & Talk Shows');
INSERT INTO genere VALUES(67,'Thrillers');
INSERT INTO genere VALUES(68,'TV Action & Adventure');
INSERT INTO genere VALUES(69,'TV Comedies');
INSERT INTO genere VALUES(70,'TV Dramas');
INSERT INTO genere VALUES(71,'TV Horror');
INSERT INTO genere VALUES(72,'TV Sci-Fi & Fantasy');
INSERT INTO genere VALUES(73,'TV Shows');