-- country
INSERT INTO country VALUES(1,'Afghanistan');
INSERT INTO country VALUES(2,'Albania');
INSERT INTO country VALUES(3,'Algeria');
INSERT INTO country VALUES(4,'Angola');
INSERT INTO country VALUES(5,'Argentina');
INSERT INTO country VALUES(6,'Armenia');
INSERT INTO country VALUES(7,'Australia');
INSERT INTO country VALUES(8,'Austria');
INSERT INTO country VALUES(9,'Azerbaijan');
INSERT INTO country VALUES(10,'Bahamas');
INSERT INTO country VALUES(11,'Bangladesh');
INSERT INTO country VALUES(12,'Belgium');
INSERT INTO country VALUES(13,'Bermuda');
INSERT INTO country VALUES(14,'Botswana');
INSERT INTO country VALUES(15,'Brazil');
INSERT INTO country VALUES(16,'Bulgaria');
INSERT INTO country VALUES(17,'Burkina Faso');
INSERT INTO country VALUES(18,'Cambodia');
INSERT INTO country VALUES(19,'Canada');
INSERT INTO country VALUES(20,'Cayman Islands');
INSERT INTO country VALUES(21,'Chile');
INSERT INTO country VALUES(22,'China');
INSERT INTO country VALUES(23,'Colombia');
INSERT INTO country VALUES(24,'Croatia');
INSERT INTO country VALUES(25,'Cuba');
INSERT INTO country VALUES(26,'Czech Republic');
INSERT INTO country VALUES(27,'Denmark');
INSERT INTO country VALUES(28,'Dominican Republic');
INSERT INTO country VALUES(29,'East Germany');
INSERT INTO country VALUES(30,'Ecuador');
INSERT INTO country VALUES(31,'Egypt');
INSERT INTO country VALUES(32,'Ethiopia');
INSERT INTO country VALUES(33,'Finland');
INSERT INTO country VALUES(34,'France');
INSERT INTO country VALUES(35,'Germany');
INSERT INTO country VALUES(36,'Ghana');
INSERT INTO country VALUES(37,'Greece');
INSERT INTO country VALUES(38,'Guatemala');
INSERT INTO country VALUES(39,'Hong Kong');
INSERT INTO country VALUES(40,'Hungary');
INSERT INTO country VALUES(41,'Iceland');
INSERT INTO country VALUES(42,'India');
INSERT INTO country VALUES(43,'Indonesia');
INSERT INTO country VALUES(44,'Iran');
INSERT INTO country VALUES(45,'Iraq');
INSERT INTO country VALUES(46,'Ireland');
INSERT INTO country VALUES(47,'Israel');
INSERT INTO country VALUES(48,'Italy');
INSERT INTO country VALUES(49,'Japan');
INSERT INTO country VALUES(50,'Jordan');
INSERT INTO country VALUES(51,'Kazakhstan');
INSERT INTO country VALUES(52,'Kenya');
INSERT INTO country VALUES(53,'Kuwait');
INSERT INTO country VALUES(54,'Latvia');
INSERT INTO country VALUES(55,'Lebanon');
INSERT INTO country VALUES(56,'Liechtenstein');
INSERT INTO country VALUES(57,'Lithuania');
INSERT INTO country VALUES(58,'Luxembourg');
INSERT INTO country VALUES(59,'Malawi');
INSERT INTO country VALUES(60,'Malaysia');
INSERT INTO country VALUES(61,'Malta');
INSERT INTO country VALUES(62,'Mexico');
INSERT INTO country VALUES(63,'Mongolia');
INSERT INTO country VALUES(64,'Montenegro');
INSERT INTO country VALUES(65,'Morocco');
INSERT INTO country VALUES(66,'Namibia');
INSERT INTO country VALUES(67,'Nepal');
INSERT INTO country VALUES(68,'Netherlands');
INSERT INTO country VALUES(69,'New Zealand');
INSERT INTO country VALUES(70,'Nicaragua');
INSERT INTO country VALUES(71,'Nigeria');
INSERT INTO country VALUES(72,'Norway');
INSERT INTO country VALUES(73,'Pakistan');
INSERT INTO country VALUES(74,'Palestine');
INSERT INTO country VALUES(75,'Panama');
INSERT INTO country VALUES(76,'Peru');
INSERT INTO country VALUES(77,'Philippines');
INSERT INTO country VALUES(78,'Poland');
INSERT INTO country VALUES(79,'Portugal');
INSERT INTO country VALUES(80,'Qatar');
INSERT INTO country VALUES(81,'Romania');
INSERT INTO country VALUES(82,'Russia');
INSERT INTO country VALUES(83,'Samoa');
INSERT INTO country VALUES(84,'Saudi Arabia');
INSERT INTO country VALUES(85,'Senegal');
INSERT INTO country VALUES(86,'Serbia');
INSERT INTO country VALUES(87,'Singapore');
INSERT INTO country VALUES(88,'Slovakia');
INSERT INTO country VALUES(89,'Slovenia');
INSERT INTO country VALUES(90,'South Africa');
INSERT INTO country VALUES(91,'South Korea');
INSERT INTO country VALUES(92,'Soviet Union');
INSERT INTO country VALUES(93,'Spain');
INSERT INTO country VALUES(94,'Sri Lanka');
INSERT INTO country VALUES(95,'Sudan');
INSERT INTO country VALUES(96,'Sweden');
INSERT INTO country VALUES(97,'Switzerland');
INSERT INTO country VALUES(98,'Syria');
INSERT INTO country VALUES(99,'Taiwan');
INSERT INTO country VALUES(100,'Thailand');
INSERT INTO country VALUES(101,'Turkey');
INSERT INTO country VALUES(102,'Uganda');
INSERT INTO country VALUES(103,'Ukraine');
INSERT INTO country VALUES(104,'United Arab Emirates');
INSERT INTO country VALUES(105,'United Kingdom');
INSERT INTO country VALUES(106,'United States');
INSERT INTO country VALUES(107,'Uruguay');
INSERT INTO country VALUES(108,'Vatican City');
INSERT INTO country VALUES(109,'Venezuela');
INSERT INTO country VALUES(110,'West Germany');
INSERT INTO country VALUES(111,'Zimbabwe');
INSERT INTO country VALUES(112,'Argentina');
INSERT INTO country VALUES(113,'Australia');
INSERT INTO country VALUES(114,'Austria');
INSERT INTO country VALUES(115,'Bangladesh');
INSERT INTO country VALUES(116,'Belarus');
INSERT INTO country VALUES(117,'Belgium');
INSERT INTO country VALUES(118,'Brazil');
INSERT INTO country VALUES(119,'Bulgaria');
INSERT INTO country VALUES(120,'Cambodia');
INSERT INTO country VALUES(121,'Cameroon');
INSERT INTO country VALUES(122,'Canada');
INSERT INTO country VALUES(123,'Chile');
INSERT INTO country VALUES(124,'China');
INSERT INTO country VALUES(125,'Colombia');
INSERT INTO country VALUES(126,'Croatia');
INSERT INTO country VALUES(127,'Cyprus');
INSERT INTO country VALUES(128,'Czech Republic');
INSERT INTO country VALUES(129,'Denmark');
INSERT INTO country VALUES(130,'Egypt');
INSERT INTO country VALUES(131,'Finland');
INSERT INTO country VALUES(132,'France');
INSERT INTO country VALUES(133,'Georgia');
INSERT INTO country VALUES(134,'Germany');
INSERT INTO country VALUES(135,'Ghana');
INSERT INTO country VALUES(136,'Greece');
INSERT INTO country VALUES(137,'Guatemala');
INSERT INTO country VALUES(138,'Hong Kong');
INSERT INTO country VALUES(139,'Hungary');
INSERT INTO country VALUES(140,'Iceland');
INSERT INTO country VALUES(141,'India');
INSERT INTO country VALUES(142,'Indonesia');
INSERT INTO country VALUES(143,'Iran');
INSERT INTO country VALUES(144,'Ireland');
INSERT INTO country VALUES(145,'Israel');
INSERT INTO country VALUES(146,'Italy');
INSERT INTO country VALUES(147,'Jamaica');
INSERT INTO country VALUES(148,'Japan');
INSERT INTO country VALUES(149,'Jordan');
INSERT INTO country VALUES(150,'Kenya');
INSERT INTO country VALUES(151,'Kuwait');
INSERT INTO country VALUES(152,'Lebanon');
INSERT INTO country VALUES(153,'Luxembourg');
INSERT INTO country VALUES(154,'Malaysia');
INSERT INTO country VALUES(155,'Mauritius');
INSERT INTO country VALUES(156,'Mexico');
INSERT INTO country VALUES(157,'Mozambique');
INSERT INTO country VALUES(158,'Namibia');
INSERT INTO country VALUES(159,'Netherlands');
INSERT INTO country VALUES(160,'New Zealand');
INSERT INTO country VALUES(161,'Nigeria');
INSERT INTO country VALUES(162,'Norway');
INSERT INTO country VALUES(163,'Pakistan');
INSERT INTO country VALUES(164,'Paraguay');
INSERT INTO country VALUES(165,'Peru');
INSERT INTO country VALUES(166,'Philippines');
INSERT INTO country VALUES(167,'Poland');
INSERT INTO country VALUES(168,'Portugal');
INSERT INTO country VALUES(169,'Puerto Rico');
INSERT INTO country VALUES(170,'Romania');
INSERT INTO country VALUES(171,'Russia');
INSERT INTO country VALUES(172,'Saudi Arabia');
INSERT INTO country VALUES(173,'Senegal');
INSERT INTO country VALUES(174,'Serbia');
INSERT INTO country VALUES(175,'Singapore');
INSERT INTO country VALUES(176,'Slovenia');
INSERT INTO country VALUES(177,'Somalia');
INSERT INTO country VALUES(178,'South Africa');
INSERT INTO country VALUES(179,'South Korea');
INSERT INTO country VALUES(180,'Soviet Union');
INSERT INTO country VALUES(181,'Spain');
INSERT INTO country VALUES(182,'Sweden');
INSERT INTO country VALUES(183,'Switzerland');
INSERT INTO country VALUES(184,'Syria');
INSERT INTO country VALUES(185,'Taiwan');
INSERT INTO country VALUES(186,'Thailand');
INSERT INTO country VALUES(187,'Turkey');
INSERT INTO country VALUES(188,'Ukraine');
INSERT INTO country VALUES(189,'United Arab Emirates');
INSERT INTO country VALUES(190,'United Kingdom');
INSERT INTO country VALUES(191,'United States');
INSERT INTO country VALUES(192,'Uruguay');
INSERT INTO country VALUES(193,'Venezuela');
INSERT INTO country VALUES(194,'Vietnam');
INSERT INTO country VALUES(195,'West Germany');
INSERT INTO country VALUES(196,'Zimbabwe');