-- TRUNCATE TABLE rating;
--rating
INSERT INTO rating VALUES(1,'G');
INSERT INTO rating VALUES(2,'NC-17');
INSERT INTO rating VALUES(3,'NR');
INSERT INTO rating VALUES(4,'PG');
INSERT INTO rating VALUES(5,'PG-13');
INSERT INTO rating VALUES(6,'R');
INSERT INTO rating VALUES(7,'TV-14');
INSERT INTO rating VALUES(8,'TV-G');
INSERT INTO rating VALUES(9,'TV-MA');
INSERT INTO rating VALUES(10,'TV-PG');
INSERT INTO rating VALUES(11,'TV-Y');
INSERT INTO rating VALUES(12,'TV-Y7');
INSERT INTO rating VALUES(13,'TV-Y7-FV');
INSERT INTO rating VALUES(14,'UR');